name: Build and Create Release

on:
  push:
    branches: [ main ]

jobs:
  generate-version:
    name: Create Version Number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Fetch all history for all tags and branches
      run: |
        git fetch --prune --depth=10000 
        TZ='America/Chicago' date +%H%M%S-%m%d%y > version.txt
    - name: Upload version.txt
      uses: actions/upload-artifact@v2
      with:
        name: version-date
        path: version.txt

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.1'
    - run: flutter pub get
    - run: sudo apt-get update -y
    - run: sudo apt-get install -y ninja-build libgtk-3-dev
    - run: flutter build linux
    - run: cd build/linux/x64/release/; tar -czvf linux-release.tar.gz *
    - name: Upload linux-release.tar.gz
      uses: actions/upload-artifact@v2
      with:
        name: linux-release
        path:  build/linux/x64/release/linux-release.tar.gz

  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.1'
    - run: flutter pub get
    - run: flutter build apk --release --split-per-abi
    - run: flutter build appbundle
    - name: Upload apks
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: build/app/outputs/apk/release/*.apk
    - name: Upload app-release.aab
      uses: actions/upload-artifact@v2
      with:
        name: android-aab
        path: build/app/outputs/bundle/release/app-release.aab

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [generate-version, build-linux, build-android]
    steps:
    - name: Get linux-release.tar.gz
      uses: actions/download-artifact@v2
      with:
        name: linux-release
    - name: Get apks
      uses: actions/download-artifact@v2
      with:
        name: android-apk
    - name: Get aab
      uses: actions/download-artifact@v2
      with:
        name: android-aab
    - name: Get version.txt
      uses: actions/download-artifact@v2
      with:
        name: version-date
    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: version.txt
    - name: Create a Release in GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.apk,build/app/outputs/bundle/release/app-release.aab,linux-release.tar.gz"
        token: ${{ secrets.GH_TOKEN }}
        tag: ${{ steps.version.outputs.content }}
        commit: ${{ github.sha }}
